CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INT NOT NULL,
    Customer_Name VARCHAR(255) NOT NULL,
    Phone_Number INT(10),
    Email_Address VARCHAR(255),

    PRIMARY KEY (CUSTOMER_ID)

);


CREATE TABLE STORECATOLOGE(
    ITEM_ID INT NOT NULL,
    Item_Name VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(10,2) NOT NULL,

    PRIMARY KEY (ITEM_ID)


);


CREATE TABLE STORE_TRANSACTION_HISTORY(
    TRANSACTION_ID INT NOT NULL,
    Customer_ID INT NOT NULL,
    Item_ID INT NOT NULL,

    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERNCE (CUSTOMERS),
    FOREIGN KEY (ITEM_ID) REFERNCE (STORECATOLOGE)
);
